### ISSUE TITLE
MapSwipe Tool does not respect layer draw order

### ISSUE THREAD

**Issue by Saijin-Naib** [lmotta/mapswipetool_plugin#12]
When swiping, the "swiped"/active layer is drawn atop of the other layers, not in the Z-Order it is in the layers list.

I've attached screenshots to show the behavior.

Proper Layer Draw Order:
![Annotation 2019-04-25 092629](https://user-images.githubusercontent.com/19295950/56739290-539ce280-673c-11e9-922d-d98347b600bd.png)

MapSwipe Layer Draw Order:
![Annotation 2019-04-25 092658](https://user-images.githubusercontent.com/19295950/56739331-69aaa300-673c-11e9-9e39-c3d9bc577268.png)

**Comment by lmotta** [comment]
The active layer is a MapSwipe Layer.

The MapSwipe Layer always stay in the top of layers, it is a curtain above
the layers..

My comments are about version 3.4 of QGIS

Em qui, 25 de abr de 2019 às 10:28, Saijin-Naib <notifications@github.com>
escreveu:

**Comment by Saijin-Naib** [comment]
So the behavior is as you intend it to be? Okay.

What do you think about an option to keep the MapSwipe layer in the original Z-Order of the layers in the Layers list from the Table of Contents? This might be more clear/desirable for many use cases.

**Comment by lmotta** [comment]
The problem is technical, the solution was to create one new
Map(QgsMapCanvasItem) with only the swipe layer and add together with the
map in canvas.

A possible solution for you, is, create a group with layers do you want put
above the others.
[image: image.png]

I hope this suggest can help you

Em qui, 25 de abr de 2019 às 12:34, Saijin-Naib <notifications@github.com>
escreveu:

**Comment by Saijin-Naib** [comment]
Ah, okay, I understand better now.

Yes and no. Unfortunately, the draw order for layers isn't really negotiable, so I must just get used to how MapSwipe draws over my other layers.

Thanks for the information!
